package com.rental_api.rental.Entity;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDateTime;

/**
 * Review entity represents a user's review for a property
 */
@Entity // Marks this class as a JPA entity
@Table(name = "review") // Maps this entity to the "review" table in the database
@Getter // Generates getter methods for all fields
@Setter // Generates setter methods for all fields
@NoArgsConstructor // Generates a no-argument constructor
@AllArgsConstructor // Generates a constructor with all fields
@ToString // Generates a toString() method
public class Review {

    @Id // Marks this field as the primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Auto-increment ID generated by database
    private Long id;

    @ManyToOne // Many reviews can belong to one user
    @JoinColumn(name = "user_id", nullable = false) // Foreign key column referencing User
    private User user;

    @ManyToOne // Many reviews can belong to one property
    @JoinColumn(name = "property_id", nullable = false) // Foreign key column referencing Property
    private Property property;

    @Column(nullable = false) // Rating is required and cannot be null
    private Integer rating;

    @Column(length = 1000) // Comment text with maximum length of 1000 characters
    private String comment;

    @Column(name = "created_at", nullable = false, updatable = false) // Stores creation timestamp, cannot be updated
    private LocalDateTime createdAt;

    @PrePersist // Runs automatically before the entity is saved
    protected void onCreate() {
        createdAt = LocalDateTime.now(); // Sets createdAt to current time
    }
}
